trigger:
  - master
  - preview
pr:
  - master
  - preview

variables:
  vswdbotLogin: vswdbot
  appiumVersion: 1.17.1
  basicOnly: false
  expoCLIVersion: latest
  nightlyBuild: false
  smokeTestDirectory: test/smoke

jobs:
  - job: Windows
    pool:
      name: "React Native smoke tests - Windows"
    timeoutInMinutes: 60
    steps:
      - checkout: self
        clean: true
      - bash: |
          cd $APPDATA && cd ../Local
          rm -rf ./Temp/metro-cache
          rm -rf ./Temp/haste-map-metro-*
          rm -rf ./Temp/react-native-*
          rm -rf ./Yarn/Cache
        displayName: Clear RN, Yarn cache
      - template: smoke-tests-common-validation.yml
