trigger:
  - master
pr:
  - master

variables:
  vswdbotLogin: vswdbot
  appiumVersion: 1.19.0
  basicOnly: false
  useCachedApplications: true
  expoCLIVersion: latest
  smokeTestDirectory: test/smoke

jobs:
  - job: Linux
    pool:
      name: "React Native smoke tests - Linux"
    timeoutInMinutes: 45
    steps:
      - checkout: self
        clean: true
      - template: smoke-tests-common-validation.yml
